version: '3.8'

services:
  map:
    build: ./map
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./map:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mapdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: